---
title: "Emails"
author: Jonathan A. Pedroza, PhD
date: today
format:
  pdf:
    toc: true
---

## Email 1 - Rushed Deadline

Hello Dr. Dunn,

My name is Jonathan Pedroza and I am currently a second year Master's student in the Health Track Psychology program at California State University, Dominguez Hills. After looking through your website and your CV I see that we have some similar interests. I am also interested in the examination of technology and well-being as my thesis examines just that. My project looks at how technology use, unhealthy eating habits, and lack of physical activity predict psychological well-being in college students. I am very interested in learning more about your work on happiness and the interaction with mobile technology.

I understand that the deadline is approaching quickly but I just wanted to inform you that I will be applying to UBC for fall 2017. I look forward to hearing back from you and possibly talking to you in the near future. I am also attaching my CV just in case you would like to see some of the work that has come out of the lab.

## Email 2


Hello Dr. Irish,

My name is Jonathan Pedroza and I am a second year Master’s student in the Health Track Psychology program at California State University, Dominguez Hills. I am looking to pursue a Ph.D. in Health/Social Psychology at North Dakota State University. My research interests include the examination of executive functioning via both cognitive testing and neuroimaging, the implementation of interventions on chronic illnesses (particularly technology-based interventions), and the impact of technology on adolescent and adults’ physical and psychological health. After reading some of your recent publications, I have become very interested in your work on health behaviors, stress, and sleep. After reading your article, Association Between Sleep and Health-Risk Behaviors in a Rural Adolescent Population, I grew interested in the connection between the lack of sleep and the likelihood of health risk behaviors in your adolescent population, especially that some of those health behaviors weren’t statistically significant. 

Your research interests are very similar to mine as I am also interested in conducting research on health behaviors such as physical activity, unhealthy eating habits, and sleep. I am actually finishing up my thesis examining if technology use, unhealthy eating, and physical activity predict worse psychological well-being in college students. 

I would love to be able to speak to you regarding your research and if you are available in the fall of 2017 to mentor an incoming graduate student. Please inform me if it would be helpful for me to provide any additional information. Thank you for your time and I hope to hear from you soon.

Best,

Jonathan Pedroza (JP)

--

Jonathan A. Pedroza

Graduate Research Assistant

George Marsh Applied Cognition Laboratory

Neuro-Imaging Lab Technician

fNIR Laboratory

Psychology Graduate Student, Health Track

CSU Dominguez Hills

## Email 3

Hello Dr. Cooper,

My name is Jonathan Pedroza and I am a second year Master’s student in the Health Track Psychology program at California State University, Dominguez Hills. I am looking to pursue a Ph.D. in Health Psychology at the University of Texas at El Paso. My research interests include the examination of executive functioning via both cognitive testing and neuroimaging, the implementation of interventions on chronic illnesses, and the impact of technology on adolescent and adults’ physical and psychological health. After reading some of your recent publications, I have become very interested in your work on preventive and health promotion for health disparities in the Latino/a population. After reading your article, A Randomized Trial of a Brief Smoking Cessation Intervention in a Light and Intermittent Hispanic Sample, it was interesting to find that your groups did not show differences based on the intervention condition but the motivation to quit was there for the immediate intervention group. 

Your research interests are very similar to mine as I am also interested in conducting research on health aspects such as physical activity, unhealthy eating habits, and I would like to learn more about tobacco cessation interventions. I am actually finishing up my thesis examining if technology use, unhealthy eating, and physical activity predict diminished psychological well-being in college students. 

I would love to be able to speak to you regarding your research and if you are available in the fall of 2017 to mentor an incoming graduate student. Please inform me if it would be helpful for me to provide any additional information. Thank you for your time and I hope to hear from you soon.

Best,

Jonathan Pedroza (JP)

--

Jonathan A. Pedroza

Graduate Research Assistant

George Marsh Applied Cognition Laboratory

Neuro-Imaging Lab Technician

fNIR Laboratory

Psychology Graduate Student, Health Track

CSU Dominguez Hills

## Sometimes You Get Dished off to Graduate Students

Hi Jonathan,

My name is Melissa Simone, and I'm a third year graduate student in Dr. Lockhart's Prevention Science lab (though I came in with a Masters, so I will be done soon!). It has been brought to my attention that you are interested in our lab, and Dr. Lockhart asked me to get in touch with you.  I guess we can start with any questions you have about USU, the program, and our lab.  

I also have some questions for you:

Are you applying from a Bachelors program, or are you working on a Masters degree?

I hear you're looking at PokemonGo and physical exercise; where do you see taking your interests next? 

What interests you about our lab? I will note that the lab website is extremely outdated.  We have been working on updating it, but Dr. Lockhart accepted a new student that started this fall, and we were waiting for her to get here to update the website!

Finally; how much do you know about Logan, UT?

I hope this isn't overwhelming! I'm generally just a curious person, so don't take these questions as some sort of "interview"--  I'm just learning more about you so that I can give you more accurate information for your position and interests.

All the best,

Melissa

## Sometimes You Get to Chat With Graduate Students

Hello Camille,

First off, I just wanted to thank you for taking time out of your busy schedule to answer my questions. I know you have no obligations to help me but thank you so much for the help. In regards to the program I was curious as to what kind of research backgrounds do people come in with? The website provides some details but I was just wondering if there were specific backgrounds that make up the majority of your cohort. I also wanted to get your opinion on the pros and cons of the program. Also, would you say that the funding provided is sufficient to live off of or is there a need for loans? Lastly, do you have any information on outcomes coming out of the prevention science program? 

I also have some questions not pertaining to the program exactly. I'd like to hear more about your research interests. I am always interested in what people are studying and researching (I guess I'm kind of a research nerd). Lastly, how do you like Eugene? 

I just wanted to thank you again for your help. Sorry for bombarding you with questions I am just really interested in the program and would like to hear more about it from a graduate student. My research interests line up with the program and I look forward to applying.

Best,

JP

--

Jonathan A. Pedroza

Graduate Research Assistant

George Marsh Applied Cognition Laboratory

Neuro-Imaging Lab Manager

fNIR Laboratory

Psychology Graduate Student, Health Track

CSU Dominguez Hills